"use client";
import {
  Box,
  ChakraProvider,
  ColorModeScript,
  Divider,
  Text,
} from "@chakra-ui/react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import NextNProgress from "nextjs-progressbar";
import theme from "../../theme";
import { useRouter } from "next/navigation";
import Headers from "./Components/head/page";
import Footers from "./Components/Footer/page";
import { useEffect } from "react";
import { createContext } from "react";
const inter = Inter({ subsets: ["latin"] });
const balcks: string[] = [];
export const ThemeContext = createContext({});
// export const metadata: Metadata = {
//   title: "MongolNFTDAO",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();

  return (
    <html lang="en">
      {/* <NextNProgress color={balcks.includes(router) ? "white" : "black"} /> */}
      {/* <div> */}
      <body className={inter.className} style={{ background: "black" }}>
        <ChakraProvider theme={theme}>
          {/* <ColorModeScript initialColorMode={theme.config.initialColorMode} /> */}
          <Box position="sticky" zIndex={100} top="0">
            <Headers />
            <Divider position="sticky" color={"#282828"} />
          </Box>
          <Box mx={"auto"}>
            <Box mx={"auto"} w={"1037px"}>
              <ThemeContext.Provider value="dark">
                {children}
              </ThemeContext.Provider>
            </Box>
          </Box>
          <Box w="100%">
            <Divider color={"#282828"} />
            <Footers />
          </Box>
        </ChakraProvider>
      </body>
      {/* </div> */}
    </html>
  );
}
