"use client";
import { Box, ChakraProvider, ColorModeScript, Text } from "@chakra-ui/react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import NextNProgress from "nextjs-progressbar";
import theme from "../../theme";
import { useRouter } from "next/navigation";
import Headers from "./Components/head/page";
import Footers from "./Components/Footer/page";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });
const balcks: string[] = [];

// export const metadata: Metadata = {
//   title: "MongolNFTDAO",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();

  return (
    // <html lang="en">
    <>
      {/* <NextNProgress color={balcks.includes(router) ? "white" : "black"} /> */}
      <ChakraProvider theme={theme}>
        <body className={inter.className} style={{ background: "black" }}>
          <ColorModeScript initialColorMode={theme.config.initialColorMode} />
          <Box mx={"auto"}>
            <Headers />
            <Box mx={"auto"} w={"1037px"} min-height="calc(100vh - 103px)">
              {children}
            </Box>
          </Box>
        </body>
        <Footers />
      </ChakraProvider>
    </>
    // </html>
  );
}
